project:
  type: website
  resources:
    - assets/docs/methods_example_bioinf.pdf
    - assets/docs/methods_example_exptl.pdf
    - assets/docs/FigureTitleLegend.pdf
    - assets/docs/ScientificWritingV39.pdf
    - assets/slides/Making_model_figures_workshop.pdf
    - assets/slides/writing_tutorial.pdf

website:
  title: "BM954 Project Pages"
  site-url: https://sipbs-compbiol.github.io/BM954-Project
  navbar:
    logo: ./assets/images/sipbs_compbio.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "Project Guidance"
        menu: 
          - text: "Key Dates (BM954)"
            href: calendar.qmd
          - text: "Key Dates (IBioIC)"
            href: calendar_ibioic.qmd
          - text: "Project Expectations"
            href: expectations.qmd
          - text: "Project and Time Management"
            href: time_management.qmd
          - text: "Primer: Environment Setup"
            href: primer_env.qmd
      - text: "Computational Biology"
        menu:
          - text: "Learning Resources"
            href: learning_resources.qmd
          - text: "Online Resources"
            href: online_resources.qmd
          - text: "Software Tools"
            href: software.qmd
      - text: "Thesis and Presentation"
        menu: 
          - text: "Writing a Thesis"
            href: thesis.qmd
          - text: "Preparing Figures"
            href: figures.qmd
          - text: "Writing Bioinformatics Methods"
            href: methods.qmd
          - text: "Presentation"
            href: presentation.qmd
          - text: "Science Communication"
            href: scicomm.qmd
          - text: "Blunt Advice About Writing"
            href: blunt_writing.qmd
      - icon: github
        href: https://github.com/sipbs-compbiol/BM954-Project
      - icon: twitter
        href: https://twitter.com/scompbiol
      - icon: rss
        href: index.xml  
  page-footer: 
    left: This site © University of Strathclyde 2024


format:
  html:
    theme: simplex
    toc: true
    css: styles.css
    embed-resources: true

editor: source

execute:
  freeze: auto
